### ISSUE TITLE
Querystring built-in API is legacy

### ISSUE THREAD

**Issue by jorgebodega** [DanielRamosAcosta/tepper#172]
Node built-in API `querystring` is legacy and the recommended one is `URLSearchParams`.

This is important due to how arrays are handled.

With `querystring`:

```
{test: ['a', 'b']} => test=a&test=b
```

With `URLSearchParams`

```
{test: ['a', 'b']} => test=a,b
```

**Comment by DanielRamosAcosta** [comment]
Ok I'll migrate it! Byt the output is still `test=a&test=b`

Check this:

```ts
const params = new URLSearchParams();
params.append('test', 'a');
params.append('test', 'b');
console.log(params.toString()); // test=a&test=b

const parsed = new URLSearchParams('test=a&test=b')
parsed.getAll("test") // ['a', 'b']
```

**Comment by gustavogr** [comment]
It may be related to this, but when sending an array of just one element, the server receives it as just a string:
```
    it("parses correctly an array with one element", async () => {
      const app = express().get("/", (req, res) => {
        res.send(req.query)
      })

      const { body } = await tepper(app)
        .get("")
        .withQuery({ tags: ["first-tag"] })
        .run()

      expect(body).toEqual({ tags: ["first-tag"] })
    })
```
    
 Output:
```
    - Expected  - 3
    + Received  + 1

      Object {
    -   "tags": Array [
    -     "first-tag",
    -   ],
    +   "tags": "first-tag",
      }
```

**Comment by gustavogr** [comment]
I just created #179 to add the test case mentioned in the previous comment.

**Comment by jorgebodega** [comment]
> It may be related to this, but when sending an array of just one element, the server receives it as just a string:
> 
> ```
>     it("parses correctly an array with one element", async () => {
>       const app = express().get("/", (req, res) => {
>         res.send(req.query)
>       })
> 
>       const { body } = await tepper(app)
>         .get("")
>         .withQuery({ tags: ["first-tag"] })
>         .run()
> 
>       expect(body).toEqual({ tags: ["first-tag"] })
>     })
> ```
> 
> Output:
> 
> ```
>     - Expected  - 3
>     + Received  + 1
> 
>       Object {
>     -   "tags": Array [
>     -     "first-tag",
>     -   ],
>     +   "tags": "first-tag",
>       }
> ```

That is just Express and how it parses the params, I had that problem before.

If you change the line: 
``` ts
.withQuery({ tags: ["first-tag"] })
```
with
``` ts
.withQuery({ "tags[]": ["first-tag"] })
```
The test works. I don't know if there is anyway to do that transformation with `URLSearchParams`.

**Comment by DanielRamosAcosta** [comment]
Hummmm... when there is a single value express understands that is a value, not an array...

A possible solution is what you are talking @jorgebodega, that tepper detects if is an array, and if so, instead of sending `tags=first-tag`, it sends `tags[]=first-tag`, what do you think @jorgebodega, @gustavogr?

**Comment by jorgebodega** [comment]
As far I can see, there is no way to do this just with core Express.

By default, Express is using core `querystring` with [`qs`](https://www.npmjs.com/package/qs) package for extended functionality.

Fastify works the same way, but users can override the parser.

So, for both of the libraries, the solution is to use `tags[]=first-tag` syntax, if I'm not mistaken.
