### ISSUE TITLE
ESM support

### ISSUE THREAD

**Issue by talentlessguy** [DanielRamosAcosta/tepper#402]
If importing in TS with Node16 / NodeNext set I get this:

![image](https://github.com/DanielRamosAcosta/tepper/assets/35937217/1b634881-4bf5-421d-99a4-a82f5a5602ff)

**Comment by DanielRamosAcosta** [comment]
I'm working on it 😄 , check #391

**Comment by DanielRamosAcosta** [comment]
I've release version 1.2.0, could you check it out and see if it works?
