### ISSUE TITLE
[Discussion] Types problems in comparation with supertest

### ISSUE THREAD

**Issue by tairosonloa** [DanielRamosAcosta/tepper#62]
I came across a problem due to a stricter typing  in this library compared to supertest:

The signature for `send()` method is
```typescript
send(body: Record<string, unknown> | Array<unknown>)
```
opposed to supertest 
```typescript
send(data?: string | object)
````
This leads to `Index signature is missing in type` error when passing classes as parameters.

For example:

```typescript

class CreateUserDto {
  // ....
}

createUserTepper = async (body: CreateUserDto) => {
    await tepper(app).post('/users').send(body) // Error: Index signature is missing in type
}

createUserTepperV2 = async (body: CreateUserDto) => {
    await tepper(app).post('/users').send(body as unknown as Record<string, unknown>) // Success, but verbose
}

createUserSupertest = async (body: CreateUserDto) => {
    await supertest(app).post('/users').send(body) // Success
}
```
I propose to relax the typing of the `send()` methods. My arguments are mainly two:
- It will speed up tests development while using this library and remove verbosity.
- `Record<string, unknown>` and `object` are equivalent types at runtime, but a big part of TypeScript's safety comes from the fact that these aren't the same, and that it'll only let you treat an object as a dictionary if it knows it's explicitly intended as one. This is what throws `Index signature is missing in type` error, and it's thought to stop you from accidentally reading and writing totally non-existent properties on objects. However, for our use case, is type safe enough to just use `object` instead of `Record<string, unknown>`.

I could work on this issue. Please, assign it to me if you agree with me in this type relaxation.

 Further reading: microsoft/TypeScript#15300

**Comment by DanielRamosAcosta** [comment]
I'm fine with the change @tairosonloa!
